#!/bin/bash

from="$1"
version="$2"
to="$3"

apt-cache show "$from=$version" | \
	egrep '^(Depends|Suggests|Provides|Conflicts|Replaces|Recommends):' | \
	sed -e 's/: /=/' -e 's/^/unsigned:/' -e "s/\\<$to\\>/$from/"
