#!/bin/bash -eu

# shellcheck disable=SC1091
. debian/debian.env
flavour="${DEBIAN#*.}"

# Rename files after copy-files has synchronized them with the base
# kernel.

# Rename the config files
while read -r orig; do
	dest="${orig%.*}.${flavour}"
	[ "$orig" = "$dest" ] && continue
	mv "$orig" "$dest"
done < <(find "${DEBIAN}/config/" -name 'config.flavour.*')

# Rename the inclusion list
while read -r orig; do
	dir=$(dirname "$orig")
	file=$(basename "$orig")
	dest="${dir}/${flavour}.${file#*.}"
	[ "$orig" = "$dest" ] && continue
	mv "$orig" "$dest"
done < <(find "${DEBIAN}/control.d/" -name '*.inclusion-list')

# Update the kernel flavour
sed -i 's/^\(flavours\s*=\s*\).*/\1'"${flavour}"'/' "${DEBIAN}/rules.d/"*.mk

# It's not necessary to update "${DEBIAN}/rules.d/*.mk" because
# hooks.mk can be used to override them.

# Update config options and the annotations file.
configs=(
	CONFIG_HYPERV_AZURE_BLOB=n
)

# Load archs supported in the configs
archs=
# shellcheck disable=SC2034
variant=
# shellcheck disable=SC1090
. "${DEBIAN}/etc/kernelconfig"

# Custom configs should be in the common config file
annot_file="${DEBIAN}/config/annotations"
for config in "${configs[@]}"; do
	# Split key and value
	key="${config%%=*}"
	val="${config#*=}"
	# Drop unused archs
	for arch_dir in "${DEBIAN}"/config/*; do
		[ ! -d "$arch_dir" ] && continue
		dir_arch="${arch_dir##*/}"
		skip=0
		for arch in ${archs}; do
			[ "$dir_arch" = "$arch" ] && skip=1
		done
		[ "$skip" -ne 0 ] && continue
		rm -rf "$arch_dir"
	done
	for config_file in "${DEBIAN}/config/config.common.ubuntu" \
				   "${DEBIAN}"/config/*/config.*; do
		# Remove any existing config
		sed -i -e "/^${key}=/d" -e "/^# ${key} /d" "$config_file"
		# Append desirable config value
		echo "${key}=${val:-n}" >> "$config_file"
	done
	# Remove any existing annotations
	sed -i -e "/^${key}\>/d" "$annot_file"
	# Append new annotations
	{
		echo -ne "${key}\tpolicy<{"
		for arch in ${archs}; do
			echo -n "'${arch}': '${val:--}',"
		done
		echo "}>"
		echo -e "${key}\tmark<ENFORCED> note<backport change>"
	} >> "$annot_file"
done
